### ISSUE TITLE
[Question] Animation and FPS

### ISSUE THREAD

**Issue by VladimirMarkelov** [17cupsofcoffee/tetra#105]
Maybe the question is broader than a single issue. There are a few unclear thing to me that are related to time measurement. Documentation does not say what is `frame_length`. As far as I understood, it is the number of tick for every frame. After some time reading the sources  I still unsure about:

1. `tick_rate` is set while initializing a context, and every tick update is called. It makes easy to calculate a length of a single tick. Does it mean that every time I had to calculate number of ticks depending on current tick_rate and required frame length in ms? More complex case: frame length is not divisible by tick length - though, I am not sure if it is frequent case
2. Default `tick_rate` is `1/60`, but on my laptop vsync limits FPS to `50`. How frequent  is update called this case? every 1/60s or 1/50s?
3. I see that `draw` receives the time elapsed since the last call. Is it possible to get somehow elapsed time in `update` - I want to pre-calculate some stuff before drawing in update(e.g, to check if an action should start). I think, I can calculate from tick_rate/FPS or use my own timer - but the latter does not look convenient

**Comment by 17cupsofcoffee** [comment]
First of all - I agree the `Animation` API isn't super intuitive! I'll likely be either rewriting some of it or adding more docs at some point.

Your understanding of `frame_length` is correct - the idea is that you call `tick` once every `update`, and the `frame_length` is how many ticks each frame should last for. This does mean that you can only specify a frame length that divides into your tick rate, which is a bit of a pain. I might make it so you call it in `draw` eventually, but that'll require me to expose some more timing functions (which, judging by your third question, is something I need to do anyway 😄)

To understand why it currently works like this (and to answer your other questions), let me describe how Tetra's game loop works:

* The `update` method will *always* be consistently called at the `tick_rate`, even if the system is running slow or your display refresh rate doesn't match the tick rate. This is so that the game physics/simulation will be deterministic (i.e. it'll work exactly the same regardless of what machine it's running on). In your example, `update` would still run at `1/60` even though your display rate is `1/50`.
* The `draw` method will be called as fast as your CPU/VSync rate will allow. This means that drawing might happen out of sync with updating (or even get skipped, if the game is running slow).
* The (poorly named!) `dt` parameter passed to `draw` represents how far between `update` calls the game loop currently is - for example, if `draw` got called exactly halfway between two ticks, `dt` would be `0.5`. This allows you to perform interpolation if you want to make things look smoother.

This is the approach demonstrated in [Game Programming Patterns](http://gameprogrammingpatterns.com/game-loop.html#play-catch-up) and the well-known '[Fix Your Timestep](https://gafferongames.com/post/fix_your_timestep/)' blog post by Glenn Fiedler.

So the reason that `Animation` currently is driven by the `update` ticks is because that was the easiest way to make the animations run at a consistent framerate regardless of how fast/slow the game itself is running. If we want to allow you to set `frame_length` in milliseconds, or to update an animation from `draw`, we'll need to add an API for figuring out exactly how fast `draw` is running - that's probably coming in 0.3 :)

Bit of a long winded and roundabout answer, but hopefully it helps! Let me know if there's still anything you don't quite understand 🙂

**Comment by VladimirMarkelov** [comment]
Thank you a lot! You are very helpful.
Since 'tick' is pre-defined and always has the same duration, I can just calculate animation in ticks and everything should works fine without any extra timers. The only trouble that animation duration must be divisible by a tick but it does not seem a big trouble - duration in ticks can be rounded up and nobody notices it if a tick is only around 20ms.

The only question remains: I know it is unlikely situation for modern computers and a simple game, but what happens if `update` works longer than one `tick`?

**Comment by 17cupsofcoffee** [comment]
The relevant bit of code is here: https://github.com/17cupsofcoffee/tetra/blob/master/src/lib.rs#L192

If your game is running slowly, the game loop may run multiple updates in a single frame to 'catch up'. You could think of this as us skipping a call to `draw` - your display framerate goes down, but the simulation stays running at a consistent rate.

You can run into issues if your game is consistently running too slow for it to catch up - if *every* `draw` is getting skipped, your game will stop rendering! That said, your game would have to be running ridiculously slow for things to get to that point, so in practice it's not that big an issue (although some game engines have an escape hatch where they turn off fixed-rate updates when things get super slow, and that might be something I add one day)!

**Comment by VladimirMarkelov** [comment]
I see. Thank you!

**Comment by 17cupsofcoffee** [comment]
@VladimirMarkelov: Just an update on this - in 0.3, [you will be able to set your animation's speed to a `Duration`](https://github.com/17cupsofcoffee/tetra/blob/master/examples/animation.rs), which doesn't have to be synced to your tick rate 😄 Thank you for the feedback on the old API, really helped me figure this out.
