### ISSUE TITLE
providing SDL2 GameController.set_rumble() in input

### ISSUE THREAD

**Issue by puppetmaster-** [17cupsofcoffee/tetra#120]
Is it possible that the sdl2.set_rumble function is offered in tetra input?

https://rust-sdl2.github.io/rust-sdl2/sdl2/controller/struct.GameController.html#method.set_rumble

I could really use them for my new game (shoot-out-your-life).

**Comment by 17cupsofcoffee** [comment]
I can definitely have a look at adding an API for controller rumble over the weekend :)

**Comment by 17cupsofcoffee** [comment]
Done 😄

I added two variants - `start_gamepad_vibration`, which will stop vibration after a specified amount of time, and `set_gamepad_vibration`, which will keep vibrating until you explicitly call `stop_gamepad_vibration`.

I've got a few more things I want to add/fix before I do a release, but 0.2.17 should be out by Monday at the latest. In the meantime, feel free to try the master version out and let me know if you have any issues.

**Comment by puppetmaster-** [comment]
great, thanks
I will test it right now and give you feedback if something doesn't work or needs to be adjusted.

**Comment by 17cupsofcoffee** [comment]
Hm, slightly tricky thing - `set_rumble` only works on SDL 2.0.9, which is newer than the version available on Ubuntu LTS (hence the CI build failing...)

I might have to modify the implemention to use the lower level haptic APIs to avoid breaking things for Linux users, which is a bit of a bummer. The API will probably stay more or less the same though.

**Comment by 17cupsofcoffee** [comment]
Agh, two more bumps in the road:

* The SDL2 crate's wrapper for the haptic API is extremely incomplete, and doesn't support some of things I'd need to use it.
* Even if it did, the haptic API doesn't support vibration for PS4 controllers. That's all I have, so I wouldn't be able to test it.

So my options are:

* Make SDL 2.0.9 a hard requirement to develop using Tetra
* Put the vibration API behind an off-by-default feature gate

I'm honestly kinda leaning towards the former, because I don't want to have to support multiple versions. Will mull it over a bit :)

**Comment by puppetmaster-** [comment]
I didn't think you'd stumble across so many obstacles. The next time I wish something easier. :-)

**Comment by 17cupsofcoffee** [comment]
Good news :D 

Turns out if I use the DS4Windows drivers for my controller, the haptic API works, so I can test it that way. I've reimplemented Tetra's API to use that instead, and it seems okay - the only downside is that the SDL2 crate only exposes simple haptic effects for the moment, so you can't control the two motors of the controller independently. I'm fine with that for now - if I want more complex effects, maybe I'll have a go at contributing back to the SDL crate.
