### ISSUE TITLE
Support non-QWERTY keyboards properly

### ISSUE THREAD

**Issue by anyputer** [17cupsofcoffee/tetra#151]
Currently, Tetra doesn't map the keyboard to a QWERTY layout. `sdl2::keyboard::Keycode` is being used instead of `sdl2::keyboard::Scancode`, which maps the physical locations of the keyboard to a QWERTY layout. Though, both kinds of input would be needed for text inputs and such.

**Comment by 17cupsofcoffee** [comment]
This is definitely something I want Tetra to be able to handle at some point - thank you for reminding me! I need to have a look at how some other engines deal with it and try to come up with a nice API.

**Comment by Tairesh** [comment]
When an application is started with the non-qwerty keyboard layout (Russian, in my case), all key codes are broken. This bug exists in many libraries including [ggez](https://github.com/ggez/ggez/issues/726), many Unity games and even Paradox Interactive games also have this bug. You just need to use `sdl2::keyboard::Keycode` instead of `sdl2::keyboard::Scancode` or provide them both.

**Comment by 17cupsofcoffee** [comment]
I'll try to revisit this soon!

My plan was to do something [similar to FNA](https://github.com/FNA-XNA/FNA/wiki/5:-FNA-Extensions#getkeyfromscancodeext) - add a new function for converting scancodes to keycodes, and then have two options available on `ContextBuilder`:

* **Use scancodes by default**
    * This would make alternate keyboard layouts work without any extra effort for the developer, but causes problems if you want to implement a key binding menu or display key prompts in your game (because `Key` no longer lines up with which key is *actually* being pressed).
* **Use keycodes by default** (the current behaviour)
    * In this mode, you'd need to generate the default bindings at first startup by mapping scancodes to keycodes. This way, `Key` matches the actual keys on the keyboard (e.g. pressing the key labelled `Q` results in a `Key::Q` event), but your game still acts the same on any keyboard layout.

I'm not sure which of those options should be the default - need to give some thought to what would be the least confusing.

**Comment by Tairesh** [comment]
If I using WASD for moving around in my game, I should be moving the same by pressing ZQSD on azerty keyboard, I don't think my game should need to know what keyboard user actually using, I just need the sdl [scancodes](https://nukep.github.io/glium-sdl2/sdl2_sys/scancode/index.html) 26, 4, 22, 7
The only case where I need the actual key is text inputting, but even there I need char/string, not keycode. So I clearly have no idea where I can use keycode instead of scancode.

**Comment by 17cupsofcoffee** [comment]
> If I using WASD for moving around in my game, I should be moving the same by pressing ZQSD on azerty keyboard, I don't think my game should need to know what keyboard user actually using, I just need the sdl scancodes 26, 4, 22, 7

One example of where you might need to know the actual keycode: if your game has a tutorial, and you want to display some text that says 'Press Z to move forward' (instead of 'Press W to move forward'), you can't do that with just the scancodes - you need to know what `26` maps to on the current keyboard layout.

That said, some games won't have those kinds of tutorials/key mapping menus, in which case just using scancodes for everything would be fine. I'm tempted to make that the default, and then have people opt-in if they need more complex handling of keyboard layouts.

> The only case where I need the actual key is text inputting, but even there I need char/string, not keycode.

Yeah, for anything that involves text input, you're better off using [`input::get_text_input`](https://docs.rs/tetra/0.6.5/tetra/input/fn.get_text_input.html) or [`Event::TextInput`](https://docs.rs/tetra/0.6.5/tetra/enum.Event.html#variant.TextInput) - these handle keyboard layout for you, as well as stuff like adding capital letters when Shift is held down.

**Comment by 17cupsofcoffee** [comment]
I've had some more discussions about this on Discord and people have convinced me that having scancodes as the default is the right move, for several reasons:

* Having things the other way around means your game is broken by default if you don't implement proper bindings, which is a pain for game jams/prototypes.
* Having the API be based on a 'standard' layout regardless of the actual device's labels would be consistent with the gamepad API (which uses Xbox-style naming even when you're using other controllers).

So I think next version, I will switch the underlying representation to `SDL_Scancode` (and potentially deprecate any enum variants that no longer have a mapping). This does rely on me figuring out a nice API for mapping back to the actual keyboard layout, though.

**Comment by 17cupsofcoffee** [comment]
I've raised PR #277 to implement this new API.
