### ISSUE TITLE
Request to add support for window icon

### ISSUE THREAD

**Issue by cralian** [17cupsofcoffee/tetra#188]
**Summary:**
Request to add a function to set the window icon.

**Why is this needed?**
On Linux I'm getting a generic "gear" icon (I'm not sure what happens on other platforms). It would be nice to be able to set something more relevant to the game.

There is [SDL_SetWindowIcon](https://wiki.libsdl.org/SDL_SetWindowIcon?highlight=%28%5CbCategoryVideo%5Cb%29%7C%28CategoryEnum%29%7C%28CategoryStruct%29), but I'm not sure what would be a good way to input the icon. The example shows raw bytes, which is probably fine - it's not a resource that needs to change much. But it's not very important how it's done.

**Comment by 17cupsofcoffee** [comment]
I've been working (very slowly) on a 'how to distribute your game' guide for [Tetra's website](tetra.seventeencups.net/), and this will almost certainly be covered in that! The main blocker is that I'm not 100% sure what the idiomatic way of doing this is on different platforms - need to do a bit of digging.

On Windows, I tend to use [`winres`](https://github.com/mxre/winres) as part of my build to set the icon and application metadata - I'm not sure if there's a similar thing for Linux.

**Comment by 17cupsofcoffee** [comment]
Okay, I did a bit more digging - it seems like on most Linux distributions, you'd want to create a [`.desktop` file](https://specifications.freedesktop.org/desktop-entry-spec/latest/index.html) in order to provide an icon/metadata for the game when launched - there's a good example of that [here](https://stackoverflow.com/a/41690936).

The places where exposing `SDL_SetWindowIcon` would be useful would be:

* If you cared about having an icon on the taskbar without needing a `.desktop` file
* If you wanted to switch icons at runtime (i.e. to display a notification icon, like Discord does)

These are both perfectly valid use cases, so I'll probably expose `SDL_SetWindowIcon` some time soon - but I think for most cases, the `.desktop` file is a better approach to start with.

I'll add this info to https://tetra.seventeencups.net/distributing later!

**Comment by cralian** [comment]
Thanks, that's really useful information, and the [distributing](https://tetra.seventeencups.net/distributing/) page is great!

**Comment by 17cupsofcoffee** [comment]
I make no promises that it's all accurate 😅 I really need to set up a Linux dual-boot on my dev machine so I can test these things myself.

**Comment by Tairesh** [comment]
Is there are any way to call `SDL_SetWindowIcon` now?

**Comment by 17cupsofcoffee** [comment]
It's supported on the `main` branch now 👍

As mentioned above, there are better ways of setting the icon as part of your build/packaging process, but if you want to change the icon at runtime (or if you just want a quick, cross-platform way of setting it without messing with builds), this function could be useful :)

It's a bit awkward that the image data has to be passed in as a `&mut` reference, but that's unavoidable due to SDL's API.
