### ISSUE TITLE
Gamepad axis range is slightly irregular

### ISSUE THREAD

**Issue by tatref** [17cupsofcoffee/tetra#191]
The raw value from SDL is divided by 32767.0

https://github.com/17cupsofcoffee/tetra/blob/0a5637ad8ed5c4d4cbc0d767e3282b49d0d9ab30/src/platform/window_sdl.rs#L509

However, from the doc, the range is [-32768, 32767]
https://wiki.libsdl.org/SDL_GameControllerGetAxis

Thus, the final value can be < -1.0

Should this be divide by 32768.0 instand?

**Comment by 17cupsofcoffee** [comment]
Dividing by `32768` would mean that the maximum mapped value would be 0.999, not 1.0. So either way, you'll run into this issue.

Looking at the codebases of other frameworks, they all seem to do something similar to map these values, although it's inconsistent which one people choose to divide by. PyGame and Love2D use `32768`, while FNA uses `32767` (it used to use `32768` but [they switched](https://github.com/FNA-XNA/FNA/commit/b8895e7481f769f61ac7c462c17d2374741332e2#diff-09b538509d13044543b8a4df51043568R963), for reasons I'm not totally clear on).

My platform abstraction layer is pretty heavily based on FNA's, which is why I chose the same approach as them.

**Comment by tatref** [comment]
Yes, I now that the upper value would not be 1.0, but I believe it's better if the bounds are strictly included in [-1, 1), instead of [-1.001, 1].

It's also possible to create a symetrical range before dividing, see:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dc8c76e80137c35d5e5ed8d11e13b6b3

I know that floating point values can get tricky. In this case, it think it works because the mantissa is 23bits wide, it's enough to convert from `i16` without precision loss.

**Comment by 17cupsofcoffee** [comment]
> It's also possible to create a symetrical range before dividing, see:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dc8c76e80137c35d5e5ed8d11e13b6b3

I believe the range isn't actually symmetrical, though - if I'm not mistaken, `0` is meant to represent an axis that is right in the center of its range. This is definitely the case for triggers, which always return `0` if they're not pressed. If we did `(sdl_value + 0.5) / 32767.5` , `0` would get mapped to `0.000015259022`, which would mean that triggers would never register as being fully released.

Looking at [Amethyst's code](https://github.com/amethyst/amethyst/blob/master/amethyst_input/src/sdl_events_system.rs#L171-L175), they handle it by checking whether the input value is `> 0` or not - I think that's the only approach that would handle this correctly for all inputs.

**Comment by 17cupsofcoffee** [comment]
I've changed the code to use the same approach as `amethyst_input`, and I now get the correct values on Windows.

I have seen some people saying that other platforms don't use the full range (e.g. `-32767` to `32767` instead of `-32768` to `32767`), but in those cases, this approach wouldn't be any less accurate than the old one, so seems like an easy win.
