### ISSUE TITLE
Animation: advance function does not consider the Timestep

### ISSUE THREAD

**Issue by puppetmaster-** [17cupsofcoffee/tetra#203]
**Summary:**
Playback speed no longer matches update speed when Timestep is fixed. (animation jerks)

**Why is this needed?**
Because the possibility of the timestep was added afterwards I think that it is not consistent anymore and the function should consider the setting. 

**Proposal**
```rust
/// Advances the animation's timer, switching the texture region if required.
    pub fn advance(&mut self, ctx: &Context) {
        match time::get_timestep(ctx){
            Timestep::Variable => self.advance_by(time::get_delta_time(ctx)),
            Timestep::Fixed(fixed) => self.advance_by(Duration::from_secs_f64(1.0 / fixed)),
        }
    }
```

**Comment by 17cupsofcoffee** [comment]
Are you calling `advance` in `update` or `draw`? It should be the latter (this definitely needs to be documented better - it's only shown in the example code, not the API docs).

If you're getting jerky animation with `advance` being called from `draw`, let me know and I'll investigate further 🙂 

**Some context for why `advance` works that way:**

A [common complaint](https://github.com/17cupsofcoffee/tetra/issues/105) with the old API from Tetra 0.2 was that the frame length *had* to be divisible by the update rate, because the animation would only get updated once per tick. If you had an animation that was designed to be played at a speed that didn't cleanly slot into the update rate, you'd have to round the timings up or down.

The new API defaults to being called from `draw` using the `delta_time`, because that way you can set an exact `Duration` for the frame, and regardless of the update rate, the animation will play at *exactly* that speed.

This does make things a little more complicated if you *do* want your animations to be updated in sync with the tick rate (e.g. if you were making a fighting game this would be important), but you can make that work using `advance_by`. I would like to find a nicer/clearer API for that, though, as it doesn't really make sense to be using `Duration` in that case.

I'll probably extract `Animation` out into a seperate crate at some point, so that I can evolve the API without having to make breaking changes to Tetra itself.

**Comment by puppetmaster-** [comment]
You are right, i am using the function in the update.
It could be that i missed something but it wouldn't have been in my mind to advance the animation in the draw.  
When I call it in the draw, the jerky animation is no longer present.

Again, something I'm using differently than it was intended. Maybe I should read the manual again.  :wink: 

The separate crate is certainly a good idea, I do something similar with the tetrapack.

**Comment by 17cupsofcoffee** [comment]
:+1: I'll update the docs to make this clearer.

**Comment by 17cupsofcoffee** [comment]
I've pushed an updated description for some of the methods:

![image](https://user-images.githubusercontent.com/784533/89717208-0c2b7b80-d9ac-11ea-86ac-89e07ac3bcea.png)

Do you think this is sufficient?

**Comment by puppetmaster-** [comment]
I think it's okay. 👍Thank you.

**Comment by 17cupsofcoffee** [comment]
Cool, thank you again for the report! It's very hard to judge how helpful docs are when you're the one writing them 😅
