### ISSUE TITLE
get_delta_time() with fixed timestep returns wrong value when frame dropped.

### ISSUE THREAD

**Issue by BezPowell** [17cupsofcoffee/tetra#211]
Apologies if this is not a bug / unsupported use case; I'm not entirely sure what is going on under the hood here.

I'm currently trying to update a game duration value on each `update()` with a fixed timestep. This works fine until a function runs that take more that 1/60th of a second. In my case creating a level and populating it with entities. When that happens and the `update()` takes longer than the timestep the new frames `get_delta_time()` seems to return a larger duration than has actually elapsed.

**Summary:**
When a game uses a fixed timestep and a `update()` call takes longer than the length of the timestep due to lots of processing (e.g. creating many entities in specs) the next call of `get_delta_time()` will start jumping up more rapidly than time has actually elapsed.

The output from printing the game's duration each frame is below to try and illustrate this:
```
0.0
0.03232253
0.049486894
0.05124064
0.11756442
0.1838882
0.25021195
0.31653574
0.33230978
0.34900445
0.36629856
0.38270423
0.3991322
0.41582197
0.43250266
0.44944182
0.46587446
0.4827281
0.49930665
0.5160201
0.53267336
0.54938954
0.56670475
0.5826711
0.599365
0.6160409
0.63271266
0.64940494
0.666086
0.6827516
0.6994531
0.7160952
0.73330975
0.74999875
0.7661038
0.782744
0.79980165
0.8164872
0.83327925
0.8499245
0.866704
0.8832318
0.9000451
0.9165895
0.93332815
0.9499393
0.96656543
0.9833864
1.0000993
1.0165976
1.0334032
1.0499406
1.0666397
1.0833269
1.1000748
1.1168267
1.1333493
1.1500493
1.1667385
1.1833947
1.2002943
1.2168031
1.2334704
1.8562778
2.4790852
3.1018927
3.7247
4.3475075
4.970315
5.5931225
6.2159295
6.838737
7.4615445
8.084352
8.707159
9.329967
9.952774
10.575582
11.198389
11.821197
12.444004
13.066812
13.689618
14.312426
14.935233
15.558041
16.180847
16.803656
17.426462
18.04927
18.672077
19.294886
19.917692
20.5405
21.163307
21.786116
22.408922
23.031729
23.654537
24.277344
24.282253
24.298931
24.31565
24.332294
24.348974
24.365728
24.382397
24.399015
24.415743
24.432467
24.449175
24.46578
24.482477
24.499117
24.516008
24.532532
24.549173
24.56584
24.5826
```
In reality, the game only ran for a total of 5 -6 seconds. The long update function started somewhere round about the 1.8 second mark, and finished according to `get_delta_time()` at about 24.2.

**Steps to reproduce:**
1. Setup a game using the default fixed timestep.
2. Create a `Duration` resource and add the result of `get_delta_time()` to it every `update()`.
2. Run a intensive calculation during the update function once.

**Expected behavior:**
`update()`should be called less frequently than the timestep while the intensive function is running and `get_delta_time()` should report the actual time that has elapsed.

***Actual behaviour***
`update()`is called less frequently than the timestep while the intensive function is running, but `get_delta_time()` returns a greater duration than has actually elapsed.

**Additional info:**
I don't really understand how `get_delta_time()` should work under these circumstances, so could be trying to do something that is totally unsupported. I'm happy to rewrite how I'm doing this if there is a better way.

**Comment by 17cupsofcoffee** [comment]
Ah, I think I see where the confusion is coming from! Will try to break it down a bit.

### Background

When running in 'fixed' timestep mode, the speed at which `update` and `draw` run is decoupled, as described in [this chapter from Game Programming Patterns](https://gameprogrammingpatterns.com/game-loop.html#play-catch-up):

* `update` runs at a fixed tick rate (defaulting to 60 times per second), which is the value you pass in when you create an instance of `Timestep::Fixed`. This is why it's called 'fixed' mode.
* `draw` runs as fast as your graphics card/vsync settings will allow. This may be completely different from your tick rate (e.g. I have a 144hz monitor, so my `draw` method runs 144 times per second with vsync on).

This means that your `update` should run deterministically on every machine (i.e. calling `update` five times should always yield the same end result), but rendering can dynamically become more or less smooth depending on the device's performance.

If your tick rate is **slower** than the frame rate, you get multiple frames drawn between updates (which you can optionally [interpolate](https://github.com/17cupsofcoffee/tetra/blob/main/examples/interpolation.rs) to make things look smoother). If your tick rate is **faster** than the frame rate, or a tick takes too long to process, multiple updates can be run in a single frame.

### The Issue

The reason I'm giving all this context is to hopefully illuminate what the docs mean on `get_delta_time`:

> Returns the amount of time that has passed **since the last frame was rendered**.

`get_delta_time` is the time since the last `draw`, not the last `update`, and in fixed timestep mode these are not necessarily the same!

In the case where you had a slow update, subsequent frames are running multiple updates to 'catch up' - for all of those updates, `get_delta_time` returns the same value, because it's still been the same amount of time since the last `draw`. This is what leads your timer to get out of sync - e.g. if it's been 0.01 seconds since the last frame, but three updates get run, you're adding 0.03, which doesn't reflect the amount of actual time that's passed!

### Fixes

If you want to keep using fixed timestep mode, the solution is pretty simple - you don't need to use `get_delta_time` in your `update` function! You can be sure that `update` will always be called at the same consistent rate, so you can either use a constant value in your calculations (`1.0 / your tick rate`) or, if you're lazy like me, just write all your calculations in 'per tick' amounts instead of 'per second' amounts :p

Alternatively, you could switch to using variable timestep mode, in which case using `get_delta_time` in your `update` is perfectly valid and expected (because `update` and `draw` will always happen in lockstep and can vary in rate).

Please let me know if there's any way I can improve the docs to make this stuff a bit clearer, I know it's not the most straightforward system! I'm thinking of renaming some of these functions/methods in 0.6 to make them a bit more obvious.

**Comment by BezPowell** [comment]
Ahhhh! Thank you so much for the explanation, that does clarify things!

I totally missed the since the last frame was rendered part of the docs, and was thinking it was since the last `update()` call. That makes perfect sense now. I was assuming that if spawning entities took forever it would slow down the update loop so `get_delta_time` would be necessary to account for that, but if rendering is slowed down to compensate I'll just use the constant value as suggested.

I'll have a proper re-read of the docs, but I suspect the confusion stems purely from me being used to variable update frequencies and not having quite got my head round having them decoupled.

Thanks again for the really quick clarification and apologies for adding a non-bug to the issue tracker.

**Comment by 17cupsofcoffee** [comment]
Absolutely no problem at all, it's good to have an issue on the tracker to point people to if they have the same issues 😄 

The docs for [`Timestep`](https://docs.rs/tetra/0.5.3/tetra/time/enum.Timestep.html#variants) have some info on how to use the two different modes - that's probably a good starting point for getting your head around how they're intended to be used. I should probably move that info into the top level module rather than having it hidden away in the `enum`'s docs...
