### ISSUE TITLE
Error after change audio output.

### ISSUE THREAD

**Issue by Im-Oab** [17cupsofcoffee/tetra#214]
**Summary:**
Change audio output from "internal speaker" to "headphone" cause runtime error.

thread 'main' panicked at 'No device name: BackendSpecific { err: BackendSpecificError { description: "core foundation unexpectedly returned null string" } }', /Users/xx/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.11.0/src/engine.rs:113:46

**Steps to reproduce:**
Change output audio before "cargo run".

**Expected behavior:**
The application should run normally.

**Additional info:**
- AirPod with a very long device name.
- macOS Catalina: 10.15.5
- tetra 0.5.4

**Comment by 17cupsofcoffee** [comment]
This is an upstream bug (https://github.com/RustAudio/cpal/issues/398) which has already been fixed, so I believe this bug will be resolved when I update to the new version of Rodio. I've been holding off on doing that because it'll be a (very minor) breaking change to Tetra, but if it's causing you issues I can prioritize it a bit more :+1:

**Comment by Im-Oab** [comment]
It's no hurry. I can wait for it to be fixed in few next updates.
