### ISSUE TITLE
Play sounds has a chance to cause an error on 0.8

### ISSUE THREAD

**Issue by Im-Oab** [17cupsofcoffee/Tetra#342]
### Summary

`rodio` has an issue with playback error on version `0.17.1`, and It is fixed on version `0.17.3`

https://github.com/RustAudio/rodio/issues/486

### Steps to Reproduce

Play sound will have a chance of causing this error.

### Additional Info
The workaround for this issue is to put the new version on `cargo.toml`

`rodio = { version = "0.17.3", optional = true, default-features = false }`

**Comment by 17cupsofcoffee** [comment]
You should be able to fix this by running `cargo update` on your project - Cargo will update to the latest server compatible  version (whatever the newest Rodio 0.17.x is) and use that instead 🙂

Similarly, new projects without a lockfile will just get the fixed version to begin with.

You're only locked to the specific version in my Cargo.toml if there's an = before the version number (e.g. `=0.17.1`) or if the fix isn't semver compatible (e.g. if the fix was in 0.18).

That said, I'll still update the version when I get chance - that'll automatically force a Rodio update when people pull the latest Tetra changes, so it seems sensible to do. Thanks for the heads up 👍
