### ISSUE TITLE
Examples fail to run if they include .resizable() in ContextBuilder

### ISSUE THREAD

**Issue by selkiebells** [17cupsofcoffee/tetra#86]
Several examples fail to run when .resizable(true) is used in the ContextBuilder. Removing the .resizable(true) causes them to run correctly. 

This is my output when an example (keyboard.rs) panics:
```
OpenGL Device: GeForce GTX 970/PCIe/SSE2
OpenGL Driver: 3.2.0 NVIDIA 417.35
OpenGL Vendor: NVIDIA Corporation
Swap Interval: VSync
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: -2147417850, kind: Other, message: "Cannot change thread mode after it is set." }', src\libcore\result.rs:1009:5
```

**Comment by 17cupsofcoffee** [comment]
Hm, my hunch is that this is being caused by https://github.com/tomaka/rodio/issues/214 - I ran into that during development, but I thought I'd fixed it...

If you move the call to `AudioContext::new` right to the beginning of the `build` method in lib.rs, does that fix the issue? If so, I'll release a new patch version tomorrow with that change in, if not, I'll have to investigate further.

Thanks for the report!

**Comment by selkiebells** [comment]
Yep, that seems to have fixed it. Thanks.
Really enjoying the framework so far!

**Comment by 17cupsofcoffee** [comment]
@selkiebells 0.2.7 (which contains the fix for this issue) has been published to crates.io. Thank you again for reporting the issue!
